spring:
  boot:
    admin:
      client:
        url: ${ADMIN-URL}
  application:
    name: ms-rest-api
server:
  port: 8002
  servlet:
    context-path: /ms-rest-api
management:
 endpoints:
    web:
      exposure:
        include: '*'
 endpoint:
   health:
     show-details: always
logging:
  file:
    name: ms-rest-api.log
    max-history: 20
    max-size: 20MB
api:
  title: ms-rest-api
  version: v1
  description: Microservice for REST API