spring:
  boot:
    admin:
      client:
        url: http://localhost:8082/rest-api-admin-server
  application:
    name: ms-rest-api
    version: v1
  #security:
    #user:
      #name: monitor
      #password: monitor123
server:
  port: 7001
  servlet:
    context-path: /ms-rest-api
management:
 endpoints:
    web:
      exposure:
        include: '*'
 endpoint:
   health:
     show-details: always
logging:
  file:
    name: ms-rest-api.log
    max-history: 20
    max-size: 20MB
api:
  title: ms-rest-api
  version: v1
  description: Microservice for REST API